services:
  postgres: # https://hub.docker.com/_/postgres
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}
    ports:
      - 5432:5432
    environment:
#      POSTGRES_DB: bitnami_keycloak
      POSTGRES_USER: e_approval
      POSTGRES_PASSWORD: "#3]O?4RGj)DE7Z!9SA5"
      APP_KC_DB_NAME: keycloak
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data/
#      - ./docker/postgres:/docker-entrypoint-initdb.d/
    networks:
      - keycloak-network

volumes:
  postgres:
networks:
  keycloak-network: